name: Build and Upload JAR

on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Grant execute permission for gradlew
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create JAR
        run: ./gradlew jar

      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build/libs/*.jar
